// Original procedural score and effects. No external audio, speech or tracking service.
export class SkyAudio {
 constructor(){this.ctx=null;this.sound=true;this.music=true;this.step=0;this.timer=null;this.battle=false;}
 start(){try{this.ctx||=new (window.AudioContext||window.webkitAudioContext)();this.ctx.resume();if(!this.timer)this.timer=setInterval(()=>this.tick(),220);}catch{}}
 tone(freq,dur,type='sine',gain=.08,delay=0,slide=0){if(!this.ctx||this.ctx.state!=='running')return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,slide),t+dur);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(Math.max(.002,gain),t+.015);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g);g.connect(this.ctx.destination);o.onended=()=>{o.disconnect();g.disconnect();};o.start(t);o.stop(t+dur+.04);}
 noise(dur=.18,gain=.04){if(!this.ctx)return;const n=Math.floor(this.ctx.sampleRate*dur),buf=this.ctx.createBuffer(1,n,this.ctx.sampleRate),a=buf.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*(1-i/n)**3;const src=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();src.buffer=buf;f.type='lowpass';f.frequency.value=1600;g.gain.value=gain;src.connect(f);f.connect(g);g.connect(this.ctx.destination);src.onended=()=>{src.disconnect();f.disconnect();g.disconnect();};src.start();}
 tick(){if(!this.music||document.hidden||!this.ctx||this.ctx.state!=='running')return;const notes=[0,7,12,14,12,7,3,7,0,7,10,14,15,14,10,7,5,12,17,19,17,12,8,12,3,10,15,17,15,10,7,10];const i=this.step++%32,root=146.83;this.tone(root*2**(notes[i]/12),.42,'sine',.026);if(i%4===0){this.tone(root/2*2**([0,0,5,3][Math.floor(i/8)]/12),.8,'triangle',.04);if(this.battle)this.tone(90,.18,'sine',.07,0,32);}if(this.battle&&i%2===0)this.noise(.055,.012);}
 fx(name){if(!this.sound||document.hidden)return;this.start();if(name==='shot'||name==='enemy'){this.tone(name==='shot'?540:290,.2,'sawtooth',.06,0,70);this.noise(.15,.045);}else if(name==='breaker'){this.tone(120,.42,'sawtooth',.09,0,32);this.tone(850,.35,'triangle',.05,0,80);this.noise(.35,.09);}else if(name==='correct'){[440,554,659,880].forEach((f,i)=>this.tone(f,.24,'sine',.07,i*.07));}else if(name==='victory'){[293,370,440,587,740,880].forEach((f,i)=>this.tone(f,.6,'triangle',.055,i*.13));}else if(name==='shield'){this.tone(220,.4,'sine',.07,0,660);}else if(name==='wrong'){this.tone(220,.2,'sine',.05);this.tone(196,.25,'sine',.04,.16);}else this.tone(660,.08,'sine',.035);}
 suspend(){this.ctx?.suspend();} resume(){if(this.ctx&&(this.sound||this.music))this.ctx.resume();}
}
