import {SkyWorld} from './world.js';
import {SkyAudio} from './audio.js';
import * as storage from './storage.js';
const $=s=>document.querySelector(s),app=$('#app'),dialog=$('#dialog'),audio=new SkyAudio();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n).toLocaleString('en-AU');
const readSetting=()=>{try{return JSON.parse(localStorage.getItem('bqSkyforgeSettingsV1')||'{}');}catch{return {};}};
const settings={sound:true,music:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,...readSetting()};audio.sound=settings.sound;audio.music=settings.music;
let state,profile,owner,world,busy=false,pending=null,draft={},photoUrl=null,renderId=0,photoBusy=false,draftReady=false,authenticated=false,noticeTimer,kit={cannon:1,armour:1,reactor:1};
const reviewId=new URL(location.href).searchParams.get('childId');
// Capture the capability for this tab. A later profile switch cannot silently retarget a queued action.
let childCapability='',parentCapability='';try{childCapability=sessionStorage.getItem('brightQuestChildCapability')||'';parentCapability=sessionStorage.getItem('brightQuestParentCapability')||'';}catch{}
function headers(){return {'content-type':'application/json','x-bq-child-capability':childCapability,'x-bq-parent-capability':parentCapability,...(profile?{'x-bq-child-id':profile.id}:{})};}
function notify(message){$('#notice').textContent=message;$('#notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').hidden=true,4800);}
function status(text){$('#saveStatus').textContent=text;}
async function api(method='GET',body){const r=await fetch(`/api/skyforge${reviewId?`?childId=${encodeURIComponent(reviewId)}`:''}`,{method,headers:headers(),credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000),...(body?{body:JSON.stringify(body)}:{})});let data;try{data=await r.json();}catch{throw new Error('The uplink did not respond. Your last saved progress is safe.');}if(!r.ok){const e=new Error(data.error||'The uplink is unavailable.');e.code=data.code;e.status=r.status;throw e;}return data;}
function startAudio(){audio.start();$('#soundButton').textContent=audio.sound?'Sound on':'Sound off';$('#soundButton').setAttribute('aria-pressed',String(audio.sound));}
function setBusy(value){busy=value;app.querySelectorAll('button,input').forEach(b=>{if(value){b.dataset.wasDisabled=b.disabled?'1':'0';b.disabled=true;}else if(b.dataset.wasDisabled!==undefined){b.disabled=b.dataset.wasDisabled==='1';delete b.dataset.wasDisabled;}});}
async function boot(){try{const data=await api();state=data.state;profile=data.profile;owner=data.owner;authenticated=true;pending=await storage.get('pending',owner);if(reviewId){renderReview();return;}try{world=new SkyWorld($('#world'),{reduced:settings.reduced,onError:show3DError});}catch{show3DError('3D could not start on this browser. Try enabling hardware acceleration or opening Chrome. Your saved progress is safe.');}
 if(reviewId){renderReview();return;}render();if(pending)showPending('An earlier action is waiting for confirmation. Retry it safely to continue.');else status(`Campaign synced · ${profile.name}`);
 }catch(e){app.innerHTML=`<section class="loading"><p class="eyebrow">BRIGHT QUEST ACCOUNT</p><h1>Meet your guardian.</h1><p>${esc(e.message)}</p><a class="primary" href="../#child/play">Open Bright Quest →</a><p class="form-note">Sign in and select your child profile, then open Skyforge from Play.</p></section>`;status('Campaign not loaded');}}
function show3DError(message){let el=$('.fallback3d');if(!el){el=document.createElement('div');el.className='fallback3d';document.querySelector('.topbar').after(el);}el.textContent=message;}
function render(){renderId++;photoBusy=false;draftReady=false;draft={answer:"",photo:null};setBusy(false);document.body.dataset.scene=state.phase==='briefing'?'art':'3d';world?.sync(state,state.phase==='forge'?kit:state.kit);audio.battle=state.phase==='battle';app.innerHTML=state.phase==='briefing'?briefing():state.phase==='training'?training():state.phase==='forge'?forge():state.phase==='battle'?battle():outcome();status(`Campaign synced · ${profile.name}`);if(state.phase==='training')loadDraft(renderId);}
function briefing(){const m=state.missionInfo;return `<section class="hero"><div class="hero-copy"><p class="eyebrow">BRIGHT QUEST ORIGINAL · EXPEDITION ${state.expedition}</p><h1>${state.mission===0?'The sky needs<br>a guardian.':esc(m.title)+'.'}</h1><p class="description">${state.mission===0?'A broken world. Twelve lost relays. One guardian powered by your thinking. Forge your titan and take command of the skies.':`The ${esc(m.enemy.toLowerCase())} is holding this relay. Work out three power codes on paper, choose your upgrades, then outsmart it in the arena.`}</p><div class="mission-tag"><b>OPERATION ${String(state.mission+1).padStart(2,'0')}</b><span>${esc(m.region)} · ${m.digitsA}-digit × ${m.digitsB}-digit</span></div><div><button class="primary" data-action="start">${state.mission===0?'Begin the expedition':'Prepare this operation'} <span>→</span></button></div><p class="hero-footnote">Bring paper, a pencil and a camera. Your progress saves.</p></div><div class="campaign-strip" aria-label="Twelve operation campaign">${state.missions.map((m,i)=>`<div class="mission-step ${i<state.mission?'done':i===state.mission?'current':''}"><strong>${i<state.mission?'✓':String(i+1).padStart(2,'0')}</strong><span>${i%4===0?esc(m.region):m.enemy==='Colossus'?'BOSS':'RELAY'}</span></div>`).join('')}</div></section>`;}
function stageHeader(label,title,right){return `<div class="stage-heading"><div><p class="eyebrow">${esc(label)}</p><h2>${esc(title)}</h2></div><span class="stage-count">${esc(right)}</span></div>`;}
function training(){const q=state.currentQuestion;return `${stageHeader('THE FORGE · OPERATION '+String(state.mission+1).padStart(2,'0'),'Thinking is your superpower.',`Power code ${state.questionIndex+1} / 3`)}<div class="training-layout"><section class="work-card" aria-label="Paper multiplication challenge"><div class="training-progress" aria-label="${state.questionIndex} of 3 power codes solved">${[0,1,2].map(i=>`<span class="${i<state.questionIndex?'filled':''}"></span>`).join('')}</div><p class="eyebrow">POWER CODE ${state.questionIndex+1}</p><div class="paper-question" aria-label="${q.a} multiplied by ${q.b}">${fmt(q.a)} <span>×</span> ${fmt(q.b)}</div><div class="paper-step"><span class="step-number">1</span><span>Work this out on paper. Use a separate line for each partial product.</span></div><div class="paper-step"><span class="step-number">2</span><span>Show your working, then enter your final answer.</span></div><div class="photo-upload"><img id="photoPreview" class="photo-preview" hidden alt="Your attached paper working"><label for="paperPhoto"><strong id="photoLabel">Add a photo of this working</strong><br><span>Camera or photo library · JPG / PNG / WebP</span><input id="paperPhoto" disabled type="file" accept="image/*" capture="environment"></label></div><form id="answerForm"><label class="answer-label" for="answer">Your final answer</label><div class="answer-row"><input id="answer" disabled name="answer" type="text" inputmode="numeric" autocomplete="off" maxlength="24" placeholder="Enter answer" aria-describedby="answerFeedback"><button class="primary" type="submit" disabled>Check →</button></div></form><p id="answerFeedback" class="feedback" role="status"></p><button class="hint-button" data-action="hint" ${q.hintUsed?'disabled':''}>${q.hintUsed?'Coaching is open':'Need a place-value hint?'}</button>${state.coaching?`<aside class="coach"><strong>Build it one line at a time.</strong><ol>${state.coaching.rows.map(r=>`<li>${esc(r.label)} = ?</li>`).join('')}</ol><p>${esc(state.coaching.tip)}</p></aside>`:''}<p class="form-note">Your typed answer is checked. The photo records your working; handwriting is not automatically marked. Photos stay on this browser/device. Answers and progress sync.</p></section><aside class="wingman-panel"><p class="eyebrow">PIP · YOUR WINGMATE</p><p>“No rush, Commander. Each correct power code earns a forge core. Three cores will bring your titan to life.”</p></aside></div>`;}
function forge(){const used=kit.cannon+kit.armour+kit.reactor;return `${stageHeader('LOADOUT · OPERATION '+String(state.mission+1).padStart(2,'0'),'Build your advantage.','3 power codes solved')}<div class="forge-layout"><section class="forge-card"><p class="eyebrow">AEGIS · GUARDIAN ${Math.floor(state.mission/4)+1}</p><h2>Your titan.<br>Your strategy.</h2><p style="font-size:12px">Three earned cores. Choose how to spend them; the equipment changes on your guardian.</p><div class="cores">${3-used} / 3 cores left to assign</div>${[['cannon','Pulse cannon','More damage with Strike and Breaker.'],['armour','Aegis armour','More hull and less incoming damage.'],['reactor','Arc reactor','More starting charge and stronger repairs.']].map(([id,name,copy])=>`<div class="kit-row"><div class="kit-row-head"><h3>${name}</h3><div class="kit-control"><button data-kit="${id}" data-delta="-1" aria-label="Remove ${name} core" ${!kit[id]?'disabled':''}>−</button><strong>${kit[id]}</strong><button data-kit="${id}" data-delta="1" aria-label="Add ${name} core" ${used>=3?'disabled':''}>+</button></div></div><p>${copy}</p></div>`).join('')}<button class="primary" data-action="deploy" ${used!==3?'disabled':''}>Deploy guardian →</button><p class="form-note">Enemy: ${esc(state.missionInfo.enemy)}. Watch its next move. A charged blast can overwhelm even heavy armour.</p></section></div>`;}
const intents={strike:['Incoming pulse','Strike to build charge. Repair if your hull is low.'],shield:['Shield raised','Breaker pierces the shield. A normal Strike does much less damage.'],charge:['Heavy blast charging','Brace reduces this hit dramatically. This is the moment to defend.']};
function battle(){const b=state.battle,[warning,tip]=intents[state.intent];return `<section class="arena" aria-label="Tactical battle"><div class="battle-head"><div class="hull-panel"><p class="eyebrow">${esc(profile.name)} · GUARDIAN</p><h3>AEGIS / MARK ${Math.floor(state.mission/4)+1}</h3><div class="hull-row"><span class="hull-bar"><i style="width:${b.hull/b.maxHull*100}%"></i></span><span>${b.hull}/${b.maxHull}</span></div></div><div class="battle-title"><h2>${esc(state.missionInfo.title)}</h2><p>OPERATION ${state.mission+1} / 12 · TURN ${b.turn+1} · CHARGE ${b.charge}/${b.maxCharge}</p></div><div class="hull-panel enemy"><p class="eyebrow">ROGUE MACHINE</p><h3>${esc(state.missionInfo.enemy.toUpperCase())}</h3><div class="hull-row"><span class="hull-bar"><i style="width:${b.enemyHull/b.maxEnemy*100}%"></i></span><span>${b.enemyHull}/${b.maxEnemy}</span></div></div></div><div class="battle-bottom"><div class="intent-banner" role="status"><strong>${warning}</strong><small>${tip}</small></div><div class="command-deck">${[['strike','Pulse strike','Reliable attack. Gains charge.','+2 CHARGE',false],['brace','Brace','Raise your shield. Reduce this hit.','+1 CHARGE',state.intent==='charge'],['breaker','Shield breaker','Heavy shot. Pierces enemy shields.','3 CHARGE',state.intent==='shield'],['repair','Field repair','Restore hull. Enemy still attacks.','2 CHARGE',b.hull<b.maxHull*.45]].map(([id,title,copy,cost,rec])=>`<button class="command ${rec?'recommended':''}" data-move="${id}" ${((id==='breaker'&&b.charge<3)||(id==='repair'&&(b.charge<2||b.hull===b.maxHull)))?'disabled':''}><strong>${title}</strong><small>${copy}</small><span class="cost">${cost}</span></button>`).join('')}</div><p class="battle-log" id="battleLog" role="status">${state.lastEvent?.type==='combat'?combatText(state.lastEvent):'Your move, Commander. The enemy acts after you.'}</p></div></section>`;}
function combatText(e){return `${e.damage?`${e.damage} enemy hull hit. `:''}${e.healing?`${e.healing} hull restored. `:''}${e.incoming?`${e.incoming} damage received.`:'Enemy disabled.'}`;}
function outcome(){const won=state.phase!=='lost',final=state.phase==='complete';return `<section class="outcome"><p class="eyebrow">${final?'ALL TWELVE RELAYS RESTORED':won?'OPERATION COMPLETE':'REGROUP · YOUR TRAINING IS SAFE'}</p><h1>${final?'You brought<br>back the dawn.':won?'Another light<br>in the sky.':'A setback.<br>A new strategy.'}</h1><p>${final?'Twelve relays. Three worlds. A guardian forged by your own thinking. Your entire training journal is saved.':won?`${esc(state.missionInfo.region)} is one step closer to safety. Your guardian is ready for the next operation.`:'The rogue machine got through your defences. Watch for its heavy blast, Brace at the right moment, and use Breaker when its shield rises.'}</p><div class="reward"><div><strong>${state.questionIndex}/3</strong><small>POWER CODES SOLVED</small></div><div><strong>${state.battle.turn}</strong><small>TACTICAL TURNS</small></div><div><strong>${state.mission+(won?1:0)}/12</strong><small>RELAYS RESTORED</small></div></div>${won?`<button class="primary" data-action="${final?'expedition':'next'}">${final?'Start a new expedition':'Next operation'} →</button>`:`<button class="primary" data-action="retry">Try this battle again →</button><button data-action="refit">Change loadout</button>`}<p class="form-note">${final?'New power codes. Your previous expeditions and answers stay in the journal.':won?'Progress saved to your Bright Quest account.':'No need to repeat the maths. Your earned cores are still yours.'}</p></section>`;}
async function loadDraft(epoch){try{const key=`${owner}:${state.currentQuestion.id}`;const loaded=await storage.get('drafts',key)||{answer:'',photo:null};if(epoch!==renderId)return;draft=loaded;$('#answer').value=draft.answer||'';if(draft.photo){const blob=await storage.get('photos',`${owner}:${draft.photo.hash}`);if(epoch!==renderId)return;if(blob)setPreview(blob);else{draft.photo=null;$('#photoLabel').textContent='Photo missing here — please attach it again';}}draftReady=true;if(!busy&&!pending)app.querySelectorAll('#answer,#paperPhoto,#answerForm button').forEach(el=>el.disabled=false);}catch(e){notify(e.message);setBusy(true);}}
function setPreview(blob){if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=URL.createObjectURL(blob);$('#photoPreview').src=photoUrl;$('#photoPreview').hidden=false;$('#photoLabel').textContent='Paper working attached ✓';}
async function persistDraft(){if(!owner||!state.currentQuestion)return;await storage.put('drafts',`${owner}:${state.currentQuestion.id}`,draft);}
async function send(action,{retry=false}={}){
 if(busy||reviewId)return;startAudio();setBusy(true);status('Saving your move…');let body;
 try{body=retry?pending:{version:state.version,operationId:crypto.randomUUID(),action};if(!body)throw new Error('No action to retry.');if(!retry){await storage.put('pending',owner,body);pending=body;}const data=await api('POST',body);await storage.remove('pending',owner);pending=null;
 const next=data.state;if(next.lastEvent?.type==='combat'){if($('#battleLog'))$('#battleLog').textContent='Command sent…';await world?.action(next.lastEvent,name=>audio.fx(name));}
 state=next;if(state.phase==='forge')kit={cannon:1,armour:1,reactor:1};render();if(state.lastEvent?.type==='answer'){if(state.lastEvent.correct){audio.fx('correct');notify('Power code accepted. Forge core earned!');}else{audio.fx('wrong');$('#answerFeedback').textContent='Not quite yet. Check each partial product and your carrying, then try again.';$('#answer').focus();}}
 if(['won','complete'].includes(state.phase))audio.fx('victory');
 }catch(e){setBusy(false);status('Save not confirmed — progress retained');if(e.status===401||e.code==='CHILD_CHANGED'||e.code==='CHILD_REQUIRED'){authenticated=false;app.innerHTML=`<section class="loading"><h2>Return to your profile.</h2><p>${esc(e.message)}</p><a class="primary" href="../#child/play">Open Bright Quest</a></section>`;dialog.close();}else if(pending){showPending(e.message,e.status===409||e.status===400);}else notify(e.message);}
}
function showPending(message,canReload=false){setBusy(true);const old=$('.retry-box');old?.remove();const el=document.createElement('section');el.className='retry-box';el.innerHTML=`<strong>Uplink needs attention</strong><p>${esc(message)}</p><button id="retrySave">Retry saved action</button>${canReload?'<button id="reloadSave">Load latest campaign</button>':''}<p class="form-note">Your paper photo and typed draft remain on this device.</p>`;app.prepend(el);$('#retrySave').onclick=()=>{setBusy(false);send(null,{retry:true});};if($('#reloadSave'))$('#reloadSave').onclick=async()=>{try{const data=await api();if(data.owner!==owner||data.profile.id!==profile.id){authenticated=false;app.innerHTML='<section class="loading"><h2>Your profile changed.</h2><a class="primary" href="../#child/play">Return to Bright Quest</a></section>';dialog.close();return;}await storage.remove('pending',owner);pending=null;state=data.state;render();}catch(e){notify(e.message);}};}
app.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action,move=e.target.closest('[data-move]')?.dataset.move,k=e.target.closest('[data-kit]');if(busy||photoBusy||!authenticated)return;if(k){kit[k.dataset.kit]+=Number(k.dataset.delta);audio.fx('click');render();return;}if(move){send({type:'move',move});return;}if(action)send(action==='deploy'?{type:action,kit}:{type:action});});
app.addEventListener('input',async e=>{if(e.target.id==='answer'){draft.answer=e.target.value;try{await persistDraft();}catch(error){notify(error.message);}}});
app.addEventListener('change',async e=>{if(e.target.id!=='paperPhoto'||busy||photoBusy)return;const file=e.target.files?.[0];if(!file)return;const qid=state.currentQuestion.id;photoBusy=true;$('#photoLabel').textContent='Preparing and saving your photo…';try{const photo=await storage.preparePhoto(file);await storage.put('photos',`${owner}:${photo.hash}`,photo.blob);if(state.currentQuestion?.id!==qid)return;draft.photo={hash:photo.hash,bytes:photo.bytes};await persistDraft();setPreview(photo.blob);}catch(error){notify(error.message);$('#photoLabel').textContent=draft.photo?'Previous photo still attached':'Photo not saved — try again';}finally{photoBusy=false;}});
app.addEventListener('submit',async e=>{if(e.target.id!=='answerForm')return;e.preventDefault();if(busy||photoBusy||!draftReady)return;if(!draft.photo){$('#answerFeedback').textContent='Add a photo of your paper working first.';$('#paperPhoto').focus();return;}const answer=$('#answer').value.trim();if(!/^\d[\d ,]*$/.test(answer)){ $('#answerFeedback').textContent='Enter a whole number, using digits.';return;}try{draft.answer=answer;await persistDraft();await send({type:'answer',questionId:state.currentQuestion.id,answer,photo:draft.photo,attemptId:crypto.randomUUID()});}catch(error){notify(error.message);}});
function showDialog(html){$('#dialogBody').innerHTML=html;dialog.showModal();}
$('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
$('#helpButton').onclick=()=>showDialog(`<p class="eyebrow">COMMANDER’S FIELD GUIDE</p><h2>Think. Forge. Command.</h2><ol><li><strong>Work on paper.</strong> Solve three multiplication power codes. Take a photo of each working and enter your final answer. No timer. Hints break the problem into place values.</li><li><strong>Build your guardian.</strong> Allocate three cores to cannon, armour or reactor. Each choice changes the equipment and battle stats.</li><li><strong>Read the enemy.</strong> Strike gains charge. Breaker pierces a raised shield. Brace against a heavy blast. Repair when you have charge and damaged hull.</li><li><strong>Restore the skies.</strong> Win to unlock the next relay. If you lose, retry or change equipment; your maths stays complete.</li></ol><p>Questions progress from 2-digit × 2-digit to 4-digit × 3-digit. Photos remain on the device that captured them; your typed answers and campaign sync to Bright Quest.</p>`);
function applySettings(){audio.sound=settings.sound;audio.music=settings.music;if(world)world.reduced=settings.reduced;try{localStorage.setItem('bqSkyforgeSettingsV1',JSON.stringify(settings));}catch{}$('#soundButton').textContent=settings.sound?'Sound on':'Sound off';$('#soundButton').setAttribute('aria-pressed',String(settings.sound));}
$('#soundButton').onclick=()=>{if(!audio.ctx){settings.sound=true;settings.music=true;}else{settings.sound=!settings.sound;settings.music=settings.sound;}applySettings();startAudio();};
$('#settingsButton').onclick=()=>{showDialog(`<p class="eyebrow">YOUR FLIGHT DECK</p><h2>Sound & motion</h2>${[['sound','Battle sound effects'],['music','Original music'],['reduced','Reduce motion']].map(([key,label])=>`<label class="setting">${label}<input type="checkbox" data-setting="${key}" ${settings[key]?'checked':''}></label>`).join('')}<p>Audio begins after you press a game control. Music and effects can be switched off separately. Reduced motion keeps tactical cues visible.</p>`);dialog.querySelectorAll('[data-setting]').forEach(input=>input.onchange=()=>{settings[input.dataset.setting]=input.checked;applySettings();startAudio();});};
function journalHTML(){return `<p class="eyebrow">${esc(profile.name)} · TRAINING EVIDENCE</p><h2>Your power-code journal.</h2><p>${state.attempts.filter(a=>a.correct).length} correct power codes · ${state.victories.length} relays restored. All attempts, corrections and hint use are retained.</p><p class="form-note">Typed answers are marked. Photos are unverified paper evidence stored on this browser/device only. A photo taken elsewhere will not appear here.</p>${state.attempts.length?state.attempts.slice().reverse().map(a=>`<article class="journal-item"><strong>${fmt(a.a)} × ${fmt(a.b)} = ${fmt(a.answer)} ${a.correct?'✓':'· Try again'}</strong><span>Expedition ${a.expedition} · Operation ${a.mission+1} · ${a.hintUsed?'Place-value hint used':'No hint used'}</span><br><button data-photo="${esc(a.photo.hash)}">View paper photo</button></article>`).join(''):'<p>Your first power code will appear here.</p>'}`;}
async function ensureOwner(){try{const data=await api();if(data.owner!==owner||data.profile.id!==profile.id){const e=new Error('Your profile changed. Return to Bright Quest.');e.status=403;throw e;}return true;}catch(e){if([401,403,409].includes(e.status)){authenticated=false;dialog.close();app.innerHTML='<section class="loading"><h2>Return to your profile.</h2><a class="primary" href="../#child/play">Open Bright Quest</a></section>';}notify(e.message);return false;}}
function wirePhotos(root){root.querySelectorAll('[data-photo]').forEach(button=>button.onclick=async()=>{if(!await ensureOwner())return;try{const blob=await storage.get('photos',`${owner}:${button.dataset.photo}`);if(!blob){notify('This photo is not on this browser. Open the journal on the device where it was taken.');return;}const url=URL.createObjectURL(blob);showDialog(`<p class="eyebrow">PAPER WORKING · NOT AUTOMATICALLY MARKED</p><h2>Your recorded working.</h2><img class="photo-full" src="${url}" alt="Photo of paper multiplication working"><p>Saved on this device. The typed answer was checked separately.</p>`);dialog.addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});}catch(e){notify(e.message);}});}
$('#journalButton').onclick=async()=>{if(!authenticated||!state){notify('Select your Bright Quest profile first.');return;}if(!await ensureOwner())return;showDialog(journalHTML());wirePhotos(dialog);};
function renderReview(){document.body.dataset.scene='art';app.innerHTML=`<section class="review-wrap">${journalHTML()}<a class="primary" href="../">Return to parent dashboard</a></section>`;wirePhotos(app);status(`Parent review · ${profile.name}`);}
document.addEventListener('visibilitychange',()=>{if(document.hidden)audio.suspend();else{audio.resume();if(authenticated&&dialog.open)ensureOwner();}});
window.addEventListener('pagehide',()=>audio.suspend());
boot();
