import * as storage from './storage.js';
import {GroveAudio} from './audio.js';

const $=selector=>document.querySelector(selector), app=$('#app'), dialog=$('#dialog');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={fire:{name:'Fire',copy:'Warm ember scales. A brighter flame.',detail:'Your dragon grows warmer ember markings and a stronger fire breath.'},storm:{name:'Storm',copy:'Storm-touched wings. Wind and lightning.',detail:'Your dragon gains storm-blue markings and a crackling wind power.'},nature:{name:'Nature',copy:'Forest-green scales. The magic of life.',detail:'Your dragon gains forest-green markings and living woodland magic.'},astral:{name:'Astral',copy:'Starlit scales. Wonder beyond the sky.',detail:'Your dragon gains violet starlight and a luminous fantasy power.'}};
const subjects={maths:'Maths',living:'Living things',world:'Our physical world'};
const stages=['Newborn','Hatchling','Little explorer','Young wanderer','Wing learner','Sky glider','Grove keeper','Cloud dancer','Star seeker','Elder dragon','Guardian of Emberwild'];
let settings={sound:false,music:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
try{settings={...settings,...JSON.parse(localStorage.getItem('bqDragonGroveSettingsV1')||'{}')};}catch{}
const audio=new GroveAudio({onError:message=>notify(message)});
let state,profile,owner,world,authenticated=false,busy=false,pending=null,selectedPath='fire',selectedPower='fire',selectedAnswer='',feedback=null,renderEpoch=0,draftReady=false,noticeTimer,history=[],historyCursor=null,review=false,draftSaving=0;
const reviewId=new URL(location.href).searchParams.get('childId');
let childCapability='',parentCapability='';
try{childCapability=sessionStorage.getItem('brightQuestChildCapability')||'';parentCapability=sessionStorage.getItem('brightQuestParentCapability')||'';}catch{}
const headers=()=>({'content-type':'application/json','x-bq-child-capability':childCapability,'x-bq-parent-capability':parentCapability,...(profile?{'x-bq-child-id':profile.id}:{})});
function status(message){$('#saveStatus').textContent=message;}
function notify(message){$('#notice').textContent=message;$('#notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').hidden=true,5200);}
function applySettings(){audio.configure(settings);world?.setReducedMotion?.(settings.reduced);if(world)world.reducedMotion=settings.reduced;document.body.classList.toggle('reduce-motion',settings.reduced);try{localStorage.setItem('bqDragonGroveSettingsV1',JSON.stringify(settings));}catch{}$('#soundButton').textContent=settings.sound?'Effects on':'Effects off';$('#soundButton').setAttribute('aria-pressed',String(settings.sound));}
async function api(method='GET',body,extra={}){const query=new URLSearchParams(reviewId?{childId:reviewId}:{});for(const[k,v]of Object.entries(extra))if(v!==null&&v!==undefined)query.set(k,v);const response=await fetch(`/api/dragon-grove${query.size?'?'+query:''}`,{method,headers:headers(),credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(18000),...(body?{body:JSON.stringify(body)}:{})});let data;try{data=await response.json();}catch{throw new Error('The grove could not reach your account. Your last confirmed progress is safe.');}if(!response.ok){const error=new Error(data.error||'Your saved adventure is temporarily unavailable.');error.status=response.status;error.code=data.code;throw error;}return data;}
function setBusy(value){busy=value;app.querySelectorAll('button,input').forEach(element=>{if(value){element.dataset.wasDisabled=String(element.disabled);element.disabled=true;}else if(element.dataset.wasDisabled!==undefined){element.disabled=element.dataset.wasDisabled==='true';delete element.dataset.wasDisabled;}});}
function accountGate(message){authenticated=false;review=Boolean(reviewId);document.body.classList.toggle('review-mode',review);$('#worldLoading').hidden=true;$('#worldNotice').hidden=true;$('#dragonSummary').hidden=true;$('#chapterMap').innerHTML='';$('.exit').href=review?'../#parent/evidence':'../#child/play';app.innerHTML=`<section class="panel loading"><p class="eyebrow">YOUR BRIGHT QUEST FAMILY</p><h2>Your dragon is waiting.</h2><p>${esc(message)}</p><a class="primary" href="${review?'../#parent/evidence':'../#child/play'}">Open Bright Quest →</a><p class="form-note">${review?'Unlock the parent dashboard, then return through Evidence.':'Sign in and choose your child profile. Open Dragon Grove from Play.'}</p></section>`;status('Adventure not loaded');if(dialog.open)dialog.close();world?.dispose();world=null;}
async function boot(){applySettings();try{const data=await api();state=data.state;profile=data.profile;owner=data.owner;review=Boolean(data.review);authenticated=true;history=data.evidence?.items||[];historyCursor=data.evidence?.nextCursor??null;document.body.classList.toggle('review-mode',review);if(review){$('.exit').href='../#parent/evidence';renderReview();return;}pending=await storage.get('pending',owner);render();if(pending)showPending('An earlier action is waiting for confirmation. Retry it safely to continue.');initialiseWorld();}catch(error){accountGate(error.message);}}
async function initialiseWorld(){
 let candidate;
 try{
  const {DragonWorld}=await import('./world.js?v=20261010-growth');if(!authenticated)return;
  candidate=new DragonWorld({canvas:$('#world'),reducedMotion:settings.reduced,onError:showWorldError});world=candidate;await candidate.init();
  if(!authenticated||world!==candidate){candidate.dispose();return;}
  updateWorld(state);$('#worldLoading').hidden=true;
 }catch(error){candidate?.dispose();if(world===candidate)world=null;if(authenticated)showWorldError('The 3D dragon could not load. Your progress is safe. Reload the scene or try Chrome with hardware acceleration.');}
}
function updateWorld(growth){try{world?.setGrowth(growth);if(growth.level)world?.setEnvironment(growth.level);}catch(error){world?.dispose();world=null;showWorldError(error);}}

function showWorldError(message){$('#worldLoading').hidden=true;const element=$('#worldNotice');element.hidden=false;element.textContent=message?.message||String(message);const button=document.createElement('button');button.textContent='Reload dragon';button.onclick=()=>{world?.dispose();world=null;element.hidden=true;$('#worldLoading').hidden=false;initialiseWorld();};element.append(document.createElement('br'),button);}
function syncWorld(){if(!state)return;updateWorld(state);$('#dragonName').textContent=state.name||'A little spark. A great adventure.';$('#dragonDescription').textContent=state.phase==='welcome'?'A newborn is waiting for someone like you.':`${stages[state.stage]} · ${state.levelInfo.title}`;$('#dragonSummary').hidden=state.phase==='welcome';$('#dragonSummary').innerHTML=`<div><strong>${state.stage} / 10</strong><small>Growth stages</small></div><div><strong>${state.stats.stature.toFixed(2)} m</strong><small>Stature</small></div><div><strong>${state.stats.strength}</strong><small>Strength</small></div><div class="path-chips">${Object.entries(state.paths).filter(([,rank])=>rank).map(([path,rank])=>`<span class="path-chip" data-path="${path}">${paths[path].name} ${rank}</span>`).join('')}</div>`;$('#chapterMap').innerHTML=state.levels.map(level=>`<span class="${state.completedLevels.includes(level.level)?'done':state.level===level.level?'current':''}" aria-label="Chapter ${level.level}: ${esc(level.title)}${state.completedLevels.includes(level.level)?', complete':''}">${state.completedLevels.includes(level.level)?'✓':String(level.level).padStart(2,'0')}</span>`).join('');$('#returnGrowth').hidden=true;audio.setScene(state.phase,state.level);}
function render(){renderEpoch++;setBusy(false);selectedAnswer='';draftReady=false;syncWorld();document.body.dataset.phase=state.phase;app.innerHTML=feedback?.type==='answer'&&feedback.correct?successPanel():state.phase==='welcome'?welcome():state.phase==='questions'?questions():state.phase==='evolution'?evolution():state.phase==='adventure'?adventure():celebration();status(`Adventure saved · ${profile.name}`);if(state.phase==='questions'&&!(feedback?.type==='answer'&&feedback.correct))loadDraft(renderEpoch);if(pending)showPending('An action is waiting for confirmation.');}
function welcome(){return `<section class="panel"><p class="eyebrow">TEN CHAPTERS. ONE EXTRAORDINARY FRIEND.</p><h2>A world to discover.<br>A dragon to grow.</h2><p class="intro-copy">Deep in Emberwild, a little dragon is ready for its first adventure. Solve curious questions, choose its powers and grow together.</p><div class="pill-row"><span class="pill">Maths & science</span><span class="pill">Four kinds of magic</span><span class="pill">Your progress saves</span></div><form id="nameForm"><label class="field-label" for="dragonNameInput">What will you call your dragon?</label><input id="dragonNameInput" type="text" maxlength="24" autocomplete="off" placeholder="e.g. Ember, Willow or Aster" required aria-describedby="nameHelp"><p id="nameHelp" class="form-note">Choose a name with letters, numbers, spaces, apostrophes or hyphens.</p><button class="primary wide" type="submit">Meet my dragon <span>→</span></button></form><p class="form-note" style="margin-top:20px">No timer. Hints whenever you need them. Every dragon grows in its own way.</p></section>`;}
function diagram(visual){if(!visual)return '';const items=visual.items||[];return `<figure class="question-diagram"><figcaption>${esc(visual.title||'Look closely')}</figcaption>${visual.rows?`<table>${visual.columns?`<thead><tr>${visual.columns.map(c=>`<th scope="col">${esc(c)}</th>`).join('')}</tr></thead>`:''}<tbody>${visual.rows.map(row=>`<tr>${row.map(cell=>`<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table>`:`<div class="diagram-items">${items.map((item,i)=>`${i&&['sequence','foodChain'].includes(visual.type)?'<span class="diagram-arrow" aria-hidden="true">→</span>':''}<div class="diagram-item">${item.asset&&iconKeys.has(item.asset)&&!['Pondweed','Duck','Cabbage plant'].includes(item.label)?`<img src="assets/science/${esc(item.asset)}.webp" alt="" loading="lazy">`:''}<span>${esc(item.label)}</span></div>`).join('')}</div>`}</figure>`;}
const iconKeys=new Set(['egg','caterpillar','butterfly','grass','grasshopper','frog','leaf','snail','bird','lizard','beetle','cloud']);
function questions(){const q=state.currentQuestion;return `<section class="panel"><div class="question-head"><p class="eyebrow">CHAPTER ${String(state.level).padStart(2,'0')} · ${subjects[q.subject]||esc(q.subject)}</p><div class="question-progress" aria-label="${state.questionIndex} of 3 questions complete">${[0,1,2].map(i=>`<span class="${i<state.questionIndex?'filled':''}"></span>`).join('')}</div></div><h2 class="question">${esc(q.prompt)}</h2>${diagram(q.visual)}<form id="answerForm">${q.type==='choice'?`<div class="choices" role="group" aria-label="Choose your answer">${q.choices.map((choice,i)=>`<button class="choice" type="button" data-choice="${esc(choice.id)}" aria-pressed="false" disabled><span class="choice-letter">${String.fromCharCode(65+i)}</span><span>${esc(choice.label)}</span></button>`).join('')}</div><button type="submit" class="primary wide" id="checkAnswer" disabled>Check my answer →</button>`:`<label class="field-label" for="answer">Your answer${q.unit?` · ${esc(q.unit)}`:''}</label><div class="answer-row"><input id="answer" type="text" inputmode="decimal" autocomplete="off" maxlength="64" placeholder="Your answer" aria-describedby="answerFeedback" disabled><button type="submit" class="primary" id="checkAnswer" disabled>Check →</button></div><p class="unit">${q.numericFormat==='integer'?'Enter a whole number.':q.numericFormat==='money'?'Enter the amount in dollars, using cents if needed.':q.numericFormat==='decimal'?'Enter a decimal number.':'You can use digits, decimals or a fraction such as 1/2.'}</p>`}</form><div id="answerFeedback" class="feedback" role="status">${feedback&&!feedback.correct?esc(feedback.explanation):''}</div><button class="hint-button" data-action="hint" ${q.hintUsed?'disabled':''}>${q.hintUsed?'Your hint':'A little help?'}</button>${q.hint?`<aside class="coach"><strong>Try this idea</strong>${esc(q.hint)}</aside>`:''}<p class="form-note">Question ${state.questionIndex+1} of 3. Think it through — there is no rush.</p></section>`;}
function successPanel(){return `<section class="panel"><p class="eyebrow">A LITTLE WISDOM. A LITTLE MAGIC.</p><h2>You've got it.</h2><div class="feedback positive"><p>${esc(feedback.explanation)}</p></div><p style="margin-top:22px">${state.phase==='evolution'?`${esc(state.name)} is ready to grow. Choose what happens next.`:`Another spark of learning for ${esc(state.name)}.`}</p><button class="primary wide" data-ui="continue">${state.phase==='evolution'?'Choose my dragon’s growth':'Keep exploring'} →</button><p class="form-note" style="margin-top:14px">Your answer is saved.</p></section>`;}
function evolution(){return `<section class="panel"><p class="eyebrow">THREE SPARKS EARNED · GROWTH ${state.stage+1} OF 10</p><h2>What will your<br>dragon become?</h2><p>Choose a new power or strengthen one you already love. Your choices stay together.</p><div class="evolution-options">${Object.entries(paths).map(([path,item])=>`<button class="evolution-option" data-path="${path}" aria-pressed="${selectedPath===path}"><img class="power-art" src="assets/powers/${path}.webp" alt=""><strong>${item.name}</strong><small>${item.copy}</small><small style="margin-top:9px">${state.paths[path]?`Rank ${state.paths[path]} → ${state.paths[path]+1}`:'Discover this power'}</small></button>`).join('')}</div><p id="evolutionPreview" class="evolution-preview">${paths[selectedPath].detail}</p><button class="primary wide" data-action="evolve">Grow with ${paths[selectedPath].name} →</button><p class="form-note" style="margin-top:14px">All four paths can complete the adventure. This choice becomes part of your dragon's story.</p></section>`;}
function adventure(){const a=state.adventure;if(!state.availablePowers.includes(selectedPower))selectedPower=state.availablePowers[0];return `<section class="panel"><p class="eyebrow">${state.level===10?'THE GRAND FINALE':'THE ADVENTURE'} · ${a.objectiveIndex+1} OF ${a.objectiveCount}</p><h2>${esc(a.title)}</h2><div class="adventure-clue">${esc(a.clue)}</div><label class="field-label">Choose your magic</label><div class="power-picker" role="group" aria-label="Earned dragon powers">${state.availablePowers.map(path=>`<button data-power="${path}" aria-pressed="${path===selectedPower}">${paths[path].name} · ${state.paths[path]}</button>`).join('')}</div><p class="field-label">Where should ${esc(state.name)} send its magic?</p><div class="target-list">${a.targets.map((target,i)=>`<button class="target-button" data-target="${esc(target.id)}" data-target-index="${i}"><span class="target-number">0${i+1}</span><span>${esc(target.label)}</span></button>`).join('')}</div><div class="feedback" id="adventureFeedback" role="status">${feedback?.type==='adventure'?esc(feedback.explanation):''}</div><p class="form-note" style="margin-top:18px">Read the clue, then choose a target. Every power can help.</p></section>`;}
function celebration(){const complete=state.phase==='complete';return `<section class="panel"><p class="eyebrow">${complete?'ALL TEN CHAPTERS COMPLETE':'CHAPTER '+state.level+' COMPLETE'}</p><h2>${complete?'You brought the<br>grove to life.':'Look how far<br>you’ve grown.'}</h2><p>${complete?`${esc(state.name)} is now a guardian of Emberwild. Thirty questions, ten choices and a whole world of small acts of courage — your adventure is part of the grove forever.`:`${esc(state.name)} is a ${stages[state.stage].toLowerCase()}. ${state.lastEvent?.explanation?esc(state.lastEvent.explanation):'A new chapter is waiting beyond the trees.'}`}</p><div class="reward-row"><div><strong>${state.stats.solved}</strong><small>QUESTIONS SOLVED</small></div><div><strong>${state.stage}</strong><small>GROWTH STEPS</small></div><div><strong>${state.completedLevels.length}</strong><small>CHAPTERS COMPLETE</small></div></div>${complete?'<button class="primary wide" data-ui="gallery">See our growth story →</button><button class="quiet wide" data-ui="journal">Open the learning journal</button><a class="fine-link" href="../#child/play">Back to Bright Quest</a>':'<button class="primary wide" data-action="next">Explore the next chapter →</button>'}<p class="form-note" style="margin-top:16px">Your dragon and every answer are saved to your Bright Quest profile.</p></section>`;}
async function saveDraft(value){
 const qid=state.currentQuestion.id,epoch=renderEpoch;draftSaving++;status('Saving draft on this device…');
 try{await storage.put('drafts',`${owner}:${qid}`,value);if(epoch===renderEpoch&&!busy&&!pending)status(`Draft saved on this device · ${profile.name}`);}
 finally{draftSaving--;}
}
async function loadDraft(epoch){try{const qid=state.currentQuestion.id,value=await storage.get('drafts',`${owner}:${qid}`)||'';if(epoch!==renderEpoch)return;if(state.currentQuestion.type==='choice'){selectedAnswer=value;app.querySelectorAll('[data-choice]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.choice===value)));}else $('#answer').value=value;draftReady=true;if(!pending&&!busy){app.querySelectorAll('#answer,[data-choice],#checkAnswer').forEach(element=>element.disabled=false);if(state.currentQuestion.type==='choice')$('#checkAnswer').disabled=!selectedAnswer;}}catch(error){notify(error.message);}}
async function safeEffect(path,options){if(!world)return;try{await Promise.race([Promise.resolve(world.playPower(path,options)),new Promise(resolve=>setTimeout(resolve,4200))]);}catch{notify('Your move is saved. The dragon effect could not play this time.');}}
async function send(action,{retry=false}={}){
 if(busy||review||!authenticated)return;audio.start();setBusy(true);status('Saving your adventure…');
 let confirmed=false;
 try{
  const body=retry?pending:{version:state.version,operationId:crypto.randomUUID(),action};
  if(!body)throw new Error('There is no action waiting to save.');
  const reserved=await storage.reserve(owner,body);pending=reserved;
  if(reserved.operationId!==body.operationId||JSON.stringify(reserved)!==JSON.stringify(body)){
   showPending('Another tab already has an action waiting to save. Your new answer remains in its draft. Review the saved action before continuing.',true);
   return;
  }
  const data=await api('POST',body);
  // The confirmed state is authoritative even if local cleanup or a visual effect fails.
  state=data.state;feedback=null;confirmed=true;
  pending=await storage.confirm(owner,body.operationId);
  const event=state.lastEvent;
  // A replay may return a newer state from another tab. Never replay a different operation's effect.
  if(!data.replayed&&(event?.type===body.action.type||event?.type==='evolution'&&body.action.type==='evolve')){
   if(event.type==='adventure'){feedback=event;if(event.correct){audio.effect(event.power);await safeEffect(event.power,{targetIndex:Number(event.targetId.split('-').at(-1))-1});}}
   if(event.type==='evolution'){updateWorld(state);audio.effect('grow');await safeEffect(event.path);}
   if(event.type==='answer'){feedback=event;audio.effect(event.correct?'correct':'try');}
  }
  if(['celebrate','complete'].includes(state.phase))audio.effect('victory');
  render();if(!dialog.open&&!pending){const heading=app.querySelector('h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
 }catch(error){
  setBusy(false);status(confirmed?'Your move is saved — device confirmation needs attention':'Save not confirmed — your progress is retained');
  if([401,403].includes(error.status)||['CHILD_CHANGED','CHILD_REQUIRED','PARENT_REQUIRED','PROFILE_CHANGED'].includes(error.code))accountGate(error.message);
  else if(pending)showPending(error.message,[400,409].includes(error.status));
  else{render();notify(error.message);}
 }
}
function showPending(message,canReload=false){setBusy(true);$('.retry-box')?.remove();const box=document.createElement('section');box.className='retry-box';box.innerHTML=`<strong>Let’s reconnect your adventure</strong><p>${esc(message)}</p><button id="retrySave">Retry saved action</button>${canReload?'<button id="reloadSave">Load latest dragon</button>':''}<p class="form-note">Retrying the same action is safe. Your answer draft stays on this device.</p>`;app.querySelector('.panel')?.prepend(box);$('#retrySave').onclick=()=>{setBusy(false);send(null,{retry:true});};if($('#reloadSave'))$('#reloadSave').onclick=async()=>{try{const clearing=pending?.operationId;const data=await api();if(data.owner!==owner||data.profile.id!==profile.id){accountGate('Your profile has changed. Return to Bright Quest to continue.');return;}pending=clearing?await storage.confirm(owner,clearing):await storage.get('pending',owner);state=data.state;feedback=null;render();if(pending)showPending('A different action is waiting in another tab. It has been kept safe.',true);}catch(error){notify(error.message);}};}
app.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button||busy||!authenticated)return;const d=button.dataset;if(d.ui==='continue'){feedback=null;render();app.focus();return;}if(d.ui==='gallery'){showGallery();return;}if(d.ui==='journal'){showJournal();return;}if(d.choice){selectedAnswer=d.choice;app.querySelectorAll('[data-choice]').forEach(el=>el.setAttribute('aria-pressed',String(el===button)));$('#checkAnswer').disabled=false;try{await saveDraft(selectedAnswer);}catch(error){notify(error.message);}return;}if(d.path){selectedPath=d.path;app.querySelectorAll('button[data-path]').forEach(el=>el.setAttribute('aria-pressed',String(el===button)));$('#evolutionPreview').textContent=paths[selectedPath].detail;app.querySelector('[data-action="evolve"]').textContent=`Grow with ${paths[selectedPath].name} →`;return;}if(d.power){selectedPower=d.power;app.querySelectorAll('[data-power]').forEach(el=>el.setAttribute('aria-pressed',String(el===button)));return;}if(d.target){send({type:'adventure',targetId:d.target,power:selectedPower});return;}if(d.action==='hint')send({type:'hint',questionId:state.currentQuestion.id});else if(d.action==='evolve')send({type:'evolve',path:selectedPath});else if(d.action==='next'){feedback=null;send({type:'next'});}});
app.addEventListener('input',async event=>{if(event.target.id!=='answer'||!state?.currentQuestion)return;try{await saveDraft(event.target.value);}catch(error){notify(error.message);}});
app.addEventListener('submit',async event=>{event.preventDefault();if(busy||!authenticated)return;if(event.target.id==='nameForm'){const name=$('#dragonNameInput').value.trim();if(!/^[\p{L}\p{M}\p{N} '\u2019-]{1,24}$/u.test(name)){notify('Choose a name using letters, numbers, spaces, apostrophes or hyphens.');return;}send({type:'begin',name});}if(event.target.id==='answerForm'&&draftReady){const answer=state.currentQuestion.type==='choice'?selectedAnswer:$('#answer').value.trim();if(!answer){$('#answerFeedback').textContent='Enter an answer or choose an option first.';return;}try{await saveDraft(answer);send({type:'answer',questionId:state.currentQuestion.id,answer});}catch(error){notify(error.message);}}});
function showDialog(title,html){$('#dialogBody').innerHTML=`<h2 id="dialogTitle">${title}</h2>${html}`;if(!dialog.open)dialog.showModal();}
$('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();});
async function verifiedRead(extra={}){
 try{
  const data=await api('GET',null,extra);
  if(data.owner!==owner||data.profile.id!==profile.id)throw Object.assign(new Error('Your profile changed. Return to Bright Quest.'),{status:401});
  if(!review&&!busy&&!pending){const shared=await storage.get('pending',owner);if(!busy&&!pending&&shared){pending=shared;showPending('Another tab has an action waiting for confirmation. Finish that saved action before continuing.',true);}}
  if(!authenticated)throw Object.assign(new Error('Your account access changed. Return to Bright Quest.'),{status:401});
  if(!busy&&!pending&&data.state.version>state.version){
   state=data.state;feedback=null;
   if(review){if(extra.before===undefined){history=data.evidence?.items||[];historyCursor=data.evidence?.nextCursor??null;}renderReview();}
   else render();
  }
  return data;
 }catch(error){if([401,403,409].includes(error.status))accountGate(error.message);throw error;}
}
const evidenceHTML=items=>items.map(item=>`<article class="journal-item"><span class="evidence-meta">CHAPTER ${item.level} · ${esc(item.type==='answer'?subjects[item.subject]||item.subject:item.type)} · ${item.at?esc(new Date(item.at).toLocaleString('en-AU')):''}</span><strong>${esc(item.prompt||item.title||(item.type==='evolution'?`Chose ${paths[item.path]?.name} growth`:item.type==='begin'?`Met ${item.name}`:item.type==='hint'?'Opened a hint':'A new chapter'))}</strong>${item.answer!==undefined?`<p>Answer: ${esc(item.answerLabel||item.answer)} · <b>${item.correct?'Correct':'Try again'}</b></p><p class="form-note">${item.hintUsed?'Hint used':'No hint used'}</p>`:''}${item.type==='adventure'?`<p>${esc(paths[item.power]?.name)} → ${esc(item.targetLabel)} · ${item.correct?'Completed':'Try again'}</p>`:''}${item.explanation||item.hint?`<p>${esc(item.explanation||item.hint)}</p>`:''}</article>`).join('');
function journalBody(){return `<p class="dialog-copy">${esc(profile.name)} · ${state.stats.solved} questions solved · ${state.completedLevels.length} chapters complete. Original attempts, corrections and hints stay in your story.</p><div id="evidenceItems">${history.length?evidenceHTML(history):'<p>Your first question will appear here.</p>'}</div>${historyCursor!==null?'<button id="moreEvidence" class="quiet wide">Load earlier entries</button>':''}`;}
async function loadMore(){const button=$('#moreEvidence');if(button)button.disabled=true;try{const data=await verifiedRead({before:historyCursor,limit:50});history.push(...(data.evidence?.items||[]));historyCursor=data.evidence?.nextCursor??null;if(review)renderReview();else{showDialog('Your learning journal.',journalBody());wireMore();}}catch(error){notify(error.message);if(button)button.disabled=false;}}
function wireMore(){if($('#moreEvidence'))$('#moreEvidence').onclick=loadMore;}
async function showJournal(){if(!authenticated){notify('Choose your Bright Quest profile first.');return;}try{const data=await verifiedRead({limit:50});history=data.evidence?.items||[];historyCursor=data.evidence?.nextCursor??null;showDialog('Your learning journal.',journalBody());wireMore();}catch(error){notify(error.message);}}
function renderReview(){app.innerHTML=`<section class="review-wrap"><p class="eyebrow">PARENT EVIDENCE · DRAGON GROVE</p><h2>Your learning journal.</h2><p>${esc(state.name||'Dragon adventure')} · ${stages[state.stage]}</p>${journalBody()}<a class="primary" href="../#parent/evidence">Return to parent dashboard</a></section>`;status(`Parent review · ${profile.name}`);wireMore();}
async function showGallery(){if(!authenticated||review)return;try{await verifiedRead();showDialog('Every stage of your story.',`<p class="dialog-copy">Choose an earned stage to see how ${esc(state.name)} has grown. Your current adventure stays saved.</p><div class="gallery-grid">${Array.from({length:11},(_,stage)=>`<button class="gallery-stage" data-gallery="${stage}" ${stage>state.stage?'disabled':''}><strong>${stage===0?'The beginning':'Growth '+stage}</strong><small>${stages[stage]}</small><small>${stage>state.stage?'Still to discover':stage===0?'Your newborn dragon':paths[state.growth[stage-1].path].name+' chosen'}</small></button>`).join('')}</div>`);dialog.querySelectorAll('[data-gallery]').forEach(button=>button.onclick=()=>{const stage=Number(button.dataset.gallery),growth=state.growth.slice(0,stage),previewPaths={fire:0,storm:0,nature:0,astral:0};growth.forEach(g=>previewPaths[g.path]++);updateWorld({stage,paths:previewPaths,growth});$('#dragonDescription').textContent=`Growth story · ${stages[stage]}`;$('#returnGrowth').hidden=false;dialog.close();});}catch(error){notify(error.message);}}
$('#returnGrowth').onclick=syncWorld;$('#journalButton').onclick=showJournal;$('#galleryButton').onclick=showGallery;
$('#soundButton').onclick=()=>{settings.sound=!settings.sound;applySettings();audio.start();};
$('#settingsButton').onclick=()=>{showDialog('Sound & movement.',`${[['sound','Enable sound effects'],['music','Play the soundtrack'],['reduced','Reduce movement and effects']].map(([key,label])=>`<label class="setting">${label}<input type="checkbox" data-setting="${key}" ${settings[key]?'checked':''}></label>`).join('')}<p class="form-note" style="margin-top:18px">Music begins after a game control is pressed. All progress cues remain visible with sound or movement off.</p>`);dialog.querySelectorAll('[data-setting]').forEach(input=>input.onchange=()=>{settings[input.dataset.setting]=input.checked;applySettings();audio.start();});};
$('#helpButton').onclick=()=>showDialog('A little guide to the grove.',`<ol class="dialog-copy"><li><strong>Think and discover.</strong> Each chapter has three maths and science questions. Type a number or choose an answer. Read the feedback and use a hint whenever you need one.</li><li><strong>Choose how to grow.</strong> Fire, Storm, Nature and Astral can all combine. Every earned stage makes your dragon bigger, stronger and more magical.</li><li><strong>Help Emberwild.</strong> Choose a power, read the adventure clue, then select the place that needs your help. A wrong answer never takes away your growth.</li><li><strong>Become a guardian.</strong> Finish ten chapters and the three-part finale. Visit Growth to see earlier stages and Journal for your learning story.</li></ol><p class="dialog-copy">Your adventure saves to your child profile. The questions move from late Year 3 through Year 4 with a little extra stretch near the end. Dragon magic belongs to the story; the science questions use real-world facts.</p>`);
$('#creditsButton').onclick=()=>showDialog('The artists behind Emberwild.',`<ul class="credits-list"><li><strong>European Dragon</strong> by Regina Cachoa (original alias Nonexistent 101). <a href="https://sketchfab.com/3d-models/european-dragon-82f393a2e6c048ad80c171ce3b3a7b87" target="_blank" rel="noopener">Original model</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>. Optimised textures, staged proportions, colour and effects for Dragon Grove.</li><li><strong>Enchanted Valley</strong> by Kevin MacLeod (incompetech.com). <a href="https://www.incompetech.com/music/royalty-free/index.html?isrc=USUAN1200093" target="_blank" rel="noopener">Music source</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>.</li><li><strong>Dragon Flap</strong> by VishwaJai · <a href="https://opengameart.org/content/dragon-flap-0" target="_blank" rel="noopener">CC0</a>. <strong>Spell 4 (fire)</strong> by Bart K. · <a href="https://opengameart.org/content/spell-4-fire" target="_blank" rel="noopener">CC BY 3.0</a>. Playback volume adjusted.</li><li>Original woodland, power artwork and flame textures created for Bright Quest with OpenAI image generation. Original game design, learning questions and additional sound synthesis. <a href="assets/credits.md" target="_blank" rel="noopener">Full asset notes</a>.</li></ul>`);
document.addEventListener('visibilitychange',()=>{if(document.hidden){audio.suspend();}else{audio.resume();if(authenticated)verifiedRead().catch(()=>{});}});
window.addEventListener('pagehide',()=>{audio.suspend();world?.dispose();});
window.addEventListener('pageshow',event=>{if(event.persisted&&authenticated&&!review){world=null;initialiseWorld();}});
// Read-only diagnostics; no fixture, answers or state mutation interface is shipped.
window.dragonGroveDiagnostics=()=>({phase:state?.phase,stage:state?.stage,level:state?.level,version:state?.version,authenticated,review,busy,draftSaved:draftSaving===0,pending:Boolean(pending),graphics:world?.diagnostics?.(),audio:audio.diagnostics()});
boot();
